### ISSUE TITLE
No module named 'dataclasses'

### ISSUE THREAD

**Issue by drdhaval2785** [kmadathil/sanskrit_parser#146]
Version - sanskrit-parser-0.1.0.post3
Error report
```bash
$ sanskrit_parser sandhi svargastrivizwapaMdyodivOBuvistavizatAvizOnAkaH
Traceback (most recent call last):
  File "/usr/local/bin/sanskrit_parser", line 5, in <module>
    from sanskrit_parser.cmd_line import cmd_line
  File "/usr/local/lib/python3.6/dist-packages/sanskrit_parser/__init__.py", line 83, in <module>
    from .api import Parser
  File "/usr/local/lib/python3.6/dist-packages/sanskrit_parser/api.py", line 54, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

**Comment by kmadathil** [comment]
Please upgrade to python 3.7
dataclasses is 3.7 specific.

**Comment by kmadathil** [comment]
I see that the README was not updated after we migrated to 3.7. I have fixed that.

**Comment by kmadathil** [comment]
$ python ../../scripts/sanskrit_parser sandhi 'स्वरव्ययं स्वर्गनाकत्रिदिवत्रिदशालयः।'
unable to import 'smart_open.gcs', disabling that module
Interpreting input loosely (strict_io set to false)
INFO     Input String: स्वरव्ययं स्वर्गनाकत्रिदिवत्रिदशालयः।
INFO     Input String in SLP1: svaravyayaM svarganAkatridivatridaSAlayaH
Splits:
INFO     Split: ['svaH', 'avyayam', 'svarga', 'nAka', 'tridiva', 'tridaSAlayaH']
INFO     Split: ['svara', 'vyayam', 'svarga', 'nAka', 'tridiva', 'tri', 'daSa', 'AlayaH']
INFO     Split: ['svara', 'vi', 'ayam', 'svarga', 'nAka', 'tridiva', 'tridaSAlayaH']
INFO     Split: ['sU', 'aH', 'avyayam', 'svarga', 'nAka', 'tridiva', 'tri', 'daSa', 'AlayaH']
INFO     Split: ['svara', 'vyayam', 'svarga', 'nAka', 'tridiva', 'tridaSAlayaH']
INFO     Split: ['svaH', 'avyayam', 'svarga', 'nAka', 'tridiva', 'tri', 'daSa', 'alayaH']
INFO     Split: ['svara', 'vi', 'ayam', 'svarga', 'nAka', 'tridiva', 'tri', 'daSa', 'alayaH']
INFO     Split: ['sU', 'aH', 'avyayam', 'svarga', 'nAka', 'tridiva', 'tridaSAlayaH']
INFO     Split: ['svara', 'vyayam', 'svarga', 'nAka', 'tridiva', 'tri', 'daSa', 'alayaH']
INFO     Split: ['sU', 'aH', 'avyayam', 'svarga', 'nAka', 'tridiva', 'tri', 'daSa', 'alayaH']

**Comment by drdhaval2785** [comment]
The issue has gone away with python3.9.1 installation on my machine.

Not only readme needs updation, but pypi package also needs updation.
Pypi still shows python3.6 as programming language at https://pypi.org/project/sanskrit-parser/

A new version which deprecates python3.6 support is needed to avoid such a problem.

**Comment by kmadathil** [comment]
Ok, I will update the pypi package and close this issue after this is up.
